export const TenantProvidersSymbols = {
  CREATE_TENANT_USE_CASE: Symbol('CREATE_TENANT_USE_CASE'),
  LIST_TENANTS_USE_CASE: Symbol('LIST_TENANTS_USE_CASE'),
  FIND_TENANT_USE_CASE: Symbol('FIND_TENANT_USE_CASE'),
} as const;
