export const TenantProvidersSymbols = {
  FIND_ALL_TENANTS_QUERY: Symbol('FIND_ALL_TENANT_QUERY'),
  FIND_ALL_TENANTS_DAO: Symbol('FIND_ALL_TENANTS_DAO'),
  FIND_TENANT_QUERY: Symbol('FIND_TENANT_QUERY'),
  FIND_TENANT_DAO: Symbol('FIND_TENANT_DAO'),
  CREATE_TENANT_COMMAND: Symbol('CREATE_TENANT_COMMAND'),
} as const;
