export const AuthProvidersSymbols = {
  REFRESH_TOKEN_USE_CASE: Symbol('REFRESH_TOKEN_USE_CASE'),
  SIGN_IN_USE_CASE: Symbol('SIGN_IN_USE_CASE'),
  FORGOT_PASSWORD_USE_CASE: Symbol('FORGOT_PASSWORD_USE_CASE'),
  SIGN_OUT_USE_CASE: Symbol('SIGN_OUT_USE_CASE'),
} as const;
