export const AuthProvidersSymbols = {
  JWT_ACCESS_TOKEN_SERVICE: Symbol('JWT_ACCESS_TOKEN_SERVICE'),
  JWT_REFRESH_TOKEN_SERVICE: Symbol('JWT_REFRESH_TOKEN_SERVICE'),
  PASSWORD_HASH_SERVICE: Symbol('PASSWORD_HASH_SERVICE'),
  SIGN_IN_USE_CASE: Symbol('SIGN_IN_USE_CASE'),
  RESET_PASSWORD_JWT_GENERATOR: Symbol('RESET_PASSWORD_JWT_GENERATOR'),
  REQUEST_PASSWORD_RESET_USE_CASE: Symbol('REQUEST_PASSWORD_RESET_USE_CASE'),
  PASSWORD_RESET_USE_CASE: Symbol('PASSWORD_RESET_USE_CASE'),
  SIGN_OUT_USE_CASE: Symbol('SIGN_OUT_USE_CASE'),
} as const;
