ALTER TABLE public.request_modules DROP COLUMN IF EXISTS wrapper_integration_id CASCADE;
-- ddl-end --
ALTER TABLE public.request_module_attempts DROP COLUMN IF EXISTS wrapper_integration_id CASCADE;
-- ddl-end --


ALTER TABLE public.vaults ADD COLUMN integration_code character varying(50) NULL;
-- ddl-end --
COMMENT ON COLUMN public.vaults.integration_code IS E'The vault integration code.';
-- ddl-end --
UPDATE public.vaults SET integration_code = wrapper_integration_id;
-- ddl-end --
ALTER TABLE public.vaults ALTER COLUMN integration_code SET NOT NULL;
-- ddl-end --
ALTER TABLE public.vaults DROP COLUMN IF EXISTS wrapper_integration_id CASCADE;
-- ddl-end --


ALTER TABLE public.processors ADD COLUMN integration_code character varying(50) NULL;
-- ddl-end --
COMMENT ON COLUMN public.processors.integration_code IS E'The processor integration code.';
-- ddl-end --
UPDATE public.processors SET integration_code = wrapper_integration_id;
-- ddl-end --
ALTER TABLE public.processors ALTER COLUMN integration_code SET NOT NULL;
-- ddl-end --
ALTER TABLE public.processors DROP COLUMN IF EXISTS wrapper_integration_id CASCADE;
-- ddl-end --


ALTER TABLE public.payment_methods ADD COLUMN integration_code character varying(50) NULL;
-- ddl-end --
COMMENT ON COLUMN public.payment_methods.integration_code IS E'The payment method integration code.';
-- ddl-end --
UPDATE public.payment_methods SET integration_code = wrapper_integration_id;
-- ddl-end --
ALTER TABLE public.payment_methods ALTER COLUMN integration_code SET NOT NULL;
-- ddl-end --
ALTER TABLE public.payment_methods DROP COLUMN IF EXISTS wrapper_integration_id CASCADE;
-- ddl-end --


ALTER TABLE public.settlement_currencies ADD COLUMN integration_code character varying(50) NULL;
-- ddl-end --
COMMENT ON COLUMN public.settlement_currencies.integration_code IS E'The settlement currency integration code.';
-- ddl-end --
UPDATE public.settlement_currencies SET integration_code = wrapper_integration_id;
-- ddl-end --
ALTER TABLE public.settlement_currencies ALTER COLUMN integration_code SET NOT NULL;
-- ddl-end --
ALTER TABLE public.settlement_currencies DROP COLUMN IF EXISTS wrapper_integration_id CASCADE;
-- ddl-end --


ALTER TABLE public.tenants ADD COLUMN integration_code character varying(50) NULL;
-- ddl-end --
COMMENT ON COLUMN public.tenants.integration_code IS E'The tenant integration code.';
-- ddl-end --
UPDATE public.tenants SET integration_code = wrapper_integration_id;
-- ddl-end --
ALTER TABLE public.tenants DROP COLUMN IF EXISTS wrapper_integration_id CASCADE;
-- ddl-end --


ALTER TABLE public.modules ADD COLUMN integration_code character varying(50) NULL;
-- ddl-end --
COMMENT ON COLUMN public.modules.integration_code IS E'The module integration code.';
-- ddl-end --
UPDATE public.modules SET integration_code = wrapper_integration_id;
-- ddl-end --
UPDATE public.modules SET integration_code = 'Payment' WHERE name = 'Payments';
-- ddl-end --
ALTER TABLE public.modules ALTER COLUMN integration_code SET NOT NULL;
-- ddl-end --
ALTER TABLE public.modules DROP COLUMN IF EXISTS wrapper_integration_id CASCADE;
-- ddl-end --


ALTER TABLE public.countries ADD COLUMN integration_code character varying(50) NULL;
-- ddl-end --
COMMENT ON COLUMN public.countries.integration_code IS E'The country integration code.';
-- ddl-end --
UPDATE public.countries SET integration_code = wrapper_integration_id;
-- ddl-end --
ALTER TABLE public.countries ALTER COLUMN integration_code SET NOT NULL;
-- ddl-end --
ALTER TABLE public.countries DROP COLUMN IF EXISTS wrapper_integration_id CASCADE;
-- ddl-end --


COMMENT ON COLUMN public.vaults.name IS E'The vault name.';
-- ddl-end --
COMMENT ON COLUMN public.vaults.is_active IS E'Whatever the vault is active. True if it is active.';
-- ddl-end --
COMMENT ON COLUMN public.processors.name IS E'The processor name.';
-- ddl-end --
COMMENT ON COLUMN public.processors.is_active IS E'Whatever the processor is active. True if it is active.';
-- ddl-end --
COMMENT ON COLUMN public.payment_methods.name IS E'The payment method name.';
-- ddl-end --
COMMENT ON COLUMN public.payment_methods.is_active IS E'Whatever the payment method is active. True if it is active.';
-- ddl-end --
COMMENT ON COLUMN public.settlement_currencies.name IS E'The settlement currency name.';
-- ddl-end --
COMMENT ON COLUMN public.settlement_currencies.is_active IS E'Whatever the settlement currency is active. True if it is active.';
-- ddl-end --
COMMENT ON COLUMN public.tenants.name IS E'The tenant name.';
-- ddl-end --
COMMENT ON COLUMN public.tenants.tenant_id IS E'The tenant id generated by the tenant module.';
-- ddl-end --
COMMENT ON COLUMN public.tenants.created_by_user_id IS E'The tenant creator user id.';
-- ddl-end --
COMMENT ON COLUMN public.tenants.created_by_user_email IS E'The tenant creator user email.';
-- ddl-end --
COMMENT ON COLUMN public.request_modules.attempts IS E'The request module number of attempts.';
-- ddl-end --
COMMENT ON COLUMN public.request_modules.request_settings IS E'The request module settings.';
-- ddl-end --
COMMENT ON COLUMN public.request_modules.request_notes IS E'The request module notes.';
-- ddl-end --
COMMENT ON COLUMN public.request_modules.api_request_body IS E'The request module api request body.';
-- ddl-end --
COMMENT ON COLUMN public.request_modules.api_response_body IS E'The request module api response body.';
-- ddl-end --
COMMENT ON COLUMN public.module_request_statuses.name IS E'The module request status name.';
-- ddl-end --
COMMENT ON COLUMN public.modules.name IS E'The module name.';
-- ddl-end --
COMMENT ON COLUMN public.modules.deploy_url IS E'The module deploy api url.';
-- ddl-end --
COMMENT ON COLUMN public.request_module_attempts.provision_api_request_body IS E'The request module attempt provision api request body.';
-- ddl-end --
COMMENT ON COLUMN public.request_module_attempts.provision_api_response_body IS E'The request module attempt provision api response body.';
-- ddl-end --
COMMENT ON COLUMN public.request_module_attempts.provision_api_response_status_code IS E'The request module attempt provision api response status code.';
-- ddl-end --
COMMENT ON COLUMN public.request_module_attempts.webhook_response_body IS E'The request module attempt webhook response body.';
-- ddl-end --
COMMENT ON COLUMN public.request_module_attempts.created_by_user_id IS E'The request module attempt creator user id.';
-- ddl-end --
COMMENT ON COLUMN public.request_module_attempt_statuses.name IS E'The request module attempt status name.';
-- ddl-end --
COMMENT ON COLUMN public.countries.name IS E'The country name.';
-- ddl-end --
COMMENT ON COLUMN public.countries.flag_svg_url IS E'The country flag svg url.';
-- ddl-end --
COMMENT ON COLUMN public.countries.native_name IS E'The country native name.';
-- ddl-end --
COMMENT ON COLUMN public.countries.code IS E'The country code.';
-- ddl-end --
COMMENT ON COLUMN public.requests.created_by_user_id IS E'The request creator user id.';
-- ddl-end --
COMMENT ON COLUMN public.requests.created_by_user_email IS E'The request creator user email.';
-- ddl-end --
COMMENT ON COLUMN public.request_statuses.name IS E'The request status name.';
-- ddl-end --
