export const PayoutProvidersSymbols = {
  FIND_ALL_PAYMENTS_QUERY: Symbol('FIND_ALL_PAYMENTS_QUERY'),
  FIND_ALL_PAYMENTS_DAO: Symbol('FIND_ALL_PAYMENTS_DAO'),
  FIND_ALL_TENANT_PAYOUT_QUERY: Symbol('FIND_ALL_TENANT_PAYOUT_QUERY'),
  FIND_ALL_TENANT_PAYOUT_DAO: Symbol('FIND_ALL_TENANT_PAYOUT_DAO'),
} as const;
