export const PayoutProvidersSymbols = {
  FIND_ALL_PAYMENTS_QUERY: Symbol('FIND_ALL_PAYMENTS_QUERY'),
  FIND_ALL_PAYMENTS_DAO: Symbol('FIND_ALL_PAYMENTS_DAO'),
  FIND_ALL_TENANT_PAYOUT_QUERY: Symbol('FIND_ALL_TENANT_PAYOUT_QUERY'),
  FIND_ALL_TENANT_PAYOUT_DAO: Symbol('FIND_ALL_TENANT_PAYOUT_DAO'),
  FIND_ALL_TENANT_BALANCES_QUERY: Symbol('FIND_ALL_TENANT_BALANCES_QUERY'),
  FIND_ALL_TENANT_BALANCES_DAO: Symbol('FIND_ALL_TENANT_BALANCES_DAO'),
  FIND_ONE_TENANT_BALANCE_QUERY: Symbol('FIND_ONE_TENANT_BALANCE_QUERY'),
  FIND_ONE_TENANT_BALANCE_DAO: Symbol('FIND_ONE_TENANT_BALANCE_DAO'),
  FIND_ALL_PAYOUT_ADJUSTMENT_TYPES_QUERY: Symbol(
    'FIND_ALL_PAYOUT_ADJUSTMENT_TYPES_QUERY',
  ),
  FIND_ALL_PAYOUT_ADJUSTMENT_TYPES_DAO: Symbol(
    'FIND_ALL_PAYOUT_ADJUSTMENT_TYPES_DAO',
  ),
  FIND_ONE_PAYOUT_SUMMARY_PREVIEW_QUERY: Symbol(
    'FIND_ONE_PAYOUT_SUMMARY_PREVIEW_QUERY',
  ),
  FIND_ONE_PAYOUT_SUMMARY_PREVIEW_DAO: Symbol(
    'FIND_ONE_PAYOUT_SUMMARY_PREVIEW_DAO',
  ),
} as const;
