export const PayoutProvidersSymbols = {
  FIND_ALL_PAYMENTS_QUERY: Symbol('FIND_ALL_PAYMENTS_QUERY'),
  FIND_ALL_PAYMENTS_DAO: Symbol('FIND_ALL_PAYMENTS_DAO'),
  FIND_ONE_TENANT_BALANCE_QUERY: Symbol('FIND_ONE_TENANT_BALANCE_QUERY'),
  FIND_ONE_TENANT_BALANCE_DAO: Symbol('FIND_ONE_TENANT_BALANCE_DAO'),
} as const;
