export const AuthProvidersSymbols = {
  JWT_ACCESS_TOKEN_SERVICE: Symbol('JWT_ACCESS_TOKEN_SERVICE'),
  JWT_REFRESH_TOKEN_SERVICE: Symbol('JWT_REFRESH_TOKEN_SERVICE'),
  PASSWORD_HASH_SERVICE: Symbol('PASSWORD_HASH_SERVICE'),
  AUTH_SIGN_IN_SERVICE: Symbol('AUTH_SIGN_IN_SERVICE'),
  SIGN_IN_USE_CASE: Symbol('SIGN_IN_USE_CASE'),
} as const;
