version: '3.8'

services:
  inspire_superportal_nestjs:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:inspire_superportal_postgres

  inspire_superportal_postgres:
    container_name: inspire_superportal_postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inspire_super_portal
    ports:
      - 5434:5432
    volumes:
      - ./pgdata:/var/lib/postgresql

volumes:
  postgres-data:

networks:
  default:
    external: true
    name: inspire-tenant-backend_devcontainer_app-network
