export const AgenciesProvidersSymbols = {
  FIND_ALL_AGENCIES_QUERY: Symbol('FIND_ALL_AGENCIES_QUERY'),
  FIND_ALL_AGENCIES_DAO: Symbol('FIND_ALL_AGENCIES_DAO'),
  FIND_ALL_USER_AGENCIES_QUERY: Symbol('FIND_ALL_USER_AGENCIES_QUERY'),
  FIND_ALL_USER_AGENCIES_DAO: Symbol('FIND_ALL_USER_AGENCIES_DAO'),
} as const;
