export const InspireApiServicesProvidersSymbols = {
  INSPIRE_TENANT_API_SERVICE: Symbol('INSPIRE_TENANT_API_SERVICE'),
  INSPIRE_PAYMENT_API_SERVICE: Symbol('INSPIRE_PAYMENT_API_SERVICE'),
  INSPIRE_SALESFORCE_API_SERVICE: Symbol('INSPIRE_SALESFORCE_API_SERVICE'),
};
