version: '3'

services:
  inspire_super_portal_postgres_test:
    container_name: inspire_super_portal_postgres_test
    image: postgres
    command: "postgres -c 'shared_buffers=128MB' -c 'fsync=off' -c 'synchronous_commit=off' -c 'full_page_writes=off' -c 'max_connections=100' -c 'client_min_messages=warning'"
    tmpfs:
      - /var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inspire_super_portal_test
    ports:
      - 5435:5432