version: '3'

services:
  inspire_super_portal_postgres:
    container_name: inspire_super_portal_postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inspire_super_portal
    ports:
      - 5434:5432
    volumes:
      - ./pgdata:/var/lib/postgresql
