export namespace TenantBalancesEnum {
  export enum Ids {}

  export enum Slugs {}

  export enum Exceptions {
    AMOUNT_IS_REQUIRED = 'exception:TENANT_BALANCE_AMOUNT_IS_REQUIRED',
    AMOUNT_MUST_BE_GREATER_OR_EQUAL_THEN_ZERO = 'exception:TENANT_BALANCE_AMOUNT_MUST_BE_GREATER_OR_EQUAL_THEN_ZERO',
    SETTLEMENT_CURRENCY_IS_REQUIRED = 'exception:TENANT_BALANCE_SETTLEMENT_CURRENCY_IS_REQUIRED',
    SETTLEMENT_CURRENCY_IS_MUST_BE_UUID = 'exception:TENANT_BALANCE_SETTLEMENT_CURRENCY_IS_MUST_BE_UUID',
  }
}
