export const UsersProvidersSymbols = {
  FIND_ALL_TENANT_USERS_QUERY: Symbol('FIND_ALL_TENANT_USERS_QUERY'),
  FIND_ALL_TENANT_USERS_DAO: Symbol('FIND_ALL_TENANT_USERS_DAO'),
  FIND_ALL_ADMIN_USERS_QUERY: Symbol('FIND_ALL_ADMIN_USERS_QUERY'),
  FIND_ALL_ADMIN_USERS_DAO: Symbol('FIND_ALL_ADMIN_USERS_DAO'),
  FIND_ONE_USER_QUERY: Symbol('FIND_ONE_USER_QUERY'),
  FIND_ONE_USER_DAO: Symbol('FIND_ONE_USER_DAO'),
  CREATE_TENANT_USER_COMMAND: Symbol('CREATE_TENANT_USER_COMMAND'),
  LINK_TENANT_USER_COMMAND: Symbol('LINK_TENANT_USER_COMMAND'),
  CREATE_TENANT_ADMIN_USER_USE_CASE: Symbol(
    'CREATE_TENANT_ADMIN_USER_USE_CASE',
  ),
} as const;
