export const UsersProvidersSymbols = {
  CREATE_TENANT_USER: Symbol('CREATE_TENANT_USER'),
  LINK_TENANT_USER_USE_CASE: Symbol('LINK_TENANT_USER_USE_CASE'),
  CREATE_TENANT_ADMIN_USER_USE_CASE: Symbol(
    'CREATE_TENANT_ADMIN_USER_USE_CASE',
  ),
} as const;
